#!/bin/bash

# Remove existing links

rm ~/.config/nvim/init.vim
rm ~/.gitignore_global
rm ~/.gitconfig
rm ~/.tern-config
rm ~/.tmux.conf
rm ~/.zshenv
rm ~/.zshrc

# Create symbolic links

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ln -s $DIR/.gitignore_global ~/.gitignore_global
ln -s $DIR/.tern-config ~/.tern-config

ln -s $DIR/init.vim ~/.config/nvim/init.vim
ln -s $DIR/.tmux.conf ~/.tmux.conf
ln -s $DIR/.gitconfig ~/.gitconfig
ln -s $DIR/.zshrc ~/.zshrc

echo "All linked up."

